homepage:
    path: /{_locale}
    controller: ScyLabs\NeptuneBundle\Controller\PageController::homeAction
    requirements:
        _locale: "[a-z]{2}"
    defaults:
        _locale: "fr"
page:
    path: /{_locale}/{slug}
    controller: ScyLabs\NeptuneBundle\Controller\PageController::pageAction
    requirements:
        slug: "[a-z-_0-9/]+"
        locale: "[a-z]{2}"