#routes_front.yaml
neptune_photo:
    resource: 'routing/photo.yaml'
neptune_front_element:
    resource: 'routing/front/element.yaml'
neptune_front_page:
    resource: 'routing/front/page.yaml'
neptune_sitemap:
    path: /sitemap.{_format}
    controller: ScyLabs\NeptuneBundle\Controller\GeneratorController::generateSiteMapAction
    requirements:
        _format: xml
