neptune_changelogs:
    path: /changelogs
    controller: ScyLabs\NeptuneBundle\Controller\MainController::changelogsAction
neptune_changelog_cookie:
    path: /changelogs/{version}
    controller: ScyLabs\NeptuneBundle\Controller\MainController::setCookieChangelogsAction

neptune_codex:
    resource: 'routing/codex.yaml'

neptune_cloning:
    resource: 'routing/cloning.yaml'
neptune_export:
    resource: 'routing/export.yaml'

neptune_import:
    resource: 'routing/import.yaml'
neptune_user:
    resource: 'routing/user.yaml'
neptune_type:
    resource: 'routing/type.yaml'
neptune_infos:
    resource: 'routing/infos.yaml'
neptune_detail:
    resource: 'routing/detail.yaml'
neptune_file:
    resource: 'routing/file.yaml'
neptune_entity:
    resource: 'routing/entity.yaml'
neptune_security:
    resource: 'routing/security.yaml'






neptune_home:
    path: /
    controller: ScyLabs\NeptuneBundle\Controller\MainController::indexAction