codex_zones:
    path: /codex/zones
    controller: ScyLabs\NeptuneBundle\Controller\CodexController::getZones

codex_import:
    path: /codex/import/{id}
    controller: ScyLabs\NeptuneBundle\Controller\CodexController::importZone

codex_maj:
    path: /codex/maj/{id}
    controller: ScyLabs\NeptuneBundle\Controller\CodexController::importZone

codex_export:
    path: /codex/export/{id}
    controller: ScyLabs\NeptuneBundle\Controller\CodexController::exportZone

codex_delete:
    path: /codex/delete/{id}
    controller: ScyLabs\NeptuneBundle\Controller\CodexController::deleteZone

codex_category:
    path: /zonecategory
    controller: ScyLabs\NeptuneBundle\Controller\CodexController::categories

codex_category_edit:
    path: /zonecategory/{id}
    controller: ScyLabs\NeptuneBundle\Controller\CodexController::editCategory
    requirements:
        id: \d+
codex_category_delete:
    path: /zonecategory/remove/{id}
    controller: ScyLabs\NeptuneBundle\Controller\CodexController::deleteCategory
    requirements:
            id: \d+
codex_category_add:
    path: /zonecategory/add
    controller: ScyLabs\NeptuneBundle\Controller\CodexController::addCategory



codex_zone_show_template:
    path: /show/{id}
    controller: ScyLabs\NeptuneBundle\Controller\CodexController::showTemplate
    requirements:
        id: \d+
    methods: ['GET']

codex_photo:
    path: /photo-show/{id}/{width}/{height}/{multiplicator}/{truncate}{monochrome}/{name}
    controller: ScyLabs\NeptuneBundle\Controller\CodexController::generateAction
    requirements:
        id: "[0-9]+"
        width: "[0-9]{1,4}"
        height: "[0-9]{0,4}"
        truncate: "[01]"
        monochrome: "(/[a-zA-Z0-9]{6}-[a-fA-F0-9]{6})?"
        multiplicator: "[0-9]{2,3}"
    defaults:
        height: 0
        multiplicator: 100
        truncate: 0
        monochrome: ""
        name: ""
