admin_file:
    path: /admin/gallery
    controller: ScyLabs\NeptuneBundle\Controller\FileController::addAction

admin_file_delete:
    path: /admin/file/delete/{id}
    controller: ScyLabs\NeptuneBundle\Controller\FileController::deleteAction
    requirements:
        id : "[0-9]+"

admin_file_link:
    path: /admin/file/link
    controller: ScyLabs\NeptuneBundle\Controller\FileController::linkAction
    methods: [POST]

admin_file_link_remove:
    path: /admin/{type}/remove/{id}
    controller: ScyLabs\NeptuneBundle\Controller\FileController::removeLinkAction
    requirements:
        type: "(photo|video|document)"
        id: "[0-9]+"

admin_file_upload:
    path: /admin/file/upload
    controller: ScyLabs\NeptuneBundle\Controller\FileController::uploadAction

admin_file_gallery_prio:
    path: /admin/{type}/{id}/files
    controller: ScyLabs\NeptuneBundle\Controller\FileController::galleryPrioAction
    requirements:
        type: "[a-z]{2,20}"
        id: "[0-9]+"

admin_file_prio:
    path: /admin/file/prio
    controller: ScyLabs\NeptuneBundle\Controller\FileController::prioAction
    methods: [POST]

