neptune_file:
    path: /gallery
    controller: ScyLabs\NeptuneBundle\Controller\FileController::addAction

neptune_file_delete:
    path: /file/delete/{id}
    controller: ScyLabs\NeptuneBundle\Controller\FileController::deleteAction
    requirements:
        id : "[0-9]+"

neptune_file_link:
    path: /file/link
    controller: ScyLabs\NeptuneBundle\Controller\FileController::linkAction
    methods: [POST]

neptune_file_link_delete:
    path: /{type}/delete/{id}
    controller: ScyLabs\NeptuneBundle\Controller\FileController::removeLinkAction
    requirements:
        type: "(photo|video|document)"
        id: "[0-9]+"

neptune_file_upload:
    path: /file/upload
    controller: ScyLabs\NeptuneBundle\Controller\FileController::uploadAction

neptune_file_gallery_prio:
    path: /{type}/{id}/files
    controller: ScyLabs\NeptuneBundle\Controller\FileController::galleryPrioAction
    requirements:
        type: "[a-z]{2,20}"
        id: "[0-9]+"

neptune_file_prio:
    path: /file/prio
    controller: ScyLabs\NeptuneBundle\Controller\FileController::prioAction
    methods: [POST]

