generatePhoto:
    path: /photo/{id}/{width}/{height}/{multiplicator}/{truncate}/{name}
    controller: ScyLabs\NeptuneBundle\Controller\PhotoController::generateAction
    requirements:
        id: "[0-9]+"
        width: "[0-9]{1,4}"
        height: "[0-9]{0,4}"
        truncate: "[01]"
        multiplicator: "[0-9]{2,3}"
    defaults:
        height: 0
        multiplicator: 100
        truncate: 0
        name: ""