neptune_type_add:
    path: /{type}/type/add
    controller: ScyLabs\NeptuneBundle\Controller\TypeController::addAction
    requirements:
        type: "[a-z]{2,20}"

neptune_type:
    path: /{type}/type
    controller: ScyLabs\NeptuneBundle\Controller\TypeController::listAction
    requirements:
        type: "[a-z]{2,20}"

neptune_type_edit:
    path: /{type}/type/{id}
    controller: ScyLabs\NeptuneBundle\Controller\TypeController::editAction
    requirements:
        id: "[0-9]+"
        type: "[a-z]{2,20}"

neptune_type_remove:
    path: /{type}/type/delete/{id}
    controller: ScyLabs\NeptuneBundle\Controller\TypeController::removeAction
    requirements:
        id: "[0-9]+"
        type: "[a-z]{2,20}"
    methods: [POST,GET]