neptune_user:
    path: /user
    controller: ScyLabs\NeptuneBundle\Controller\UserController::listingAction

neptune_user_active:
    path: /user/active/{id}
    controller: ScyLabs\NeptuneBundle\Controller\UserController::switchActiveAction
    requirements:
        type: "[a-z]{2,20}"
        id: "[0-9]+"

neptune_user_add:
    path: /user/add
    controller: ScyLabs\NeptuneBundle\Controller\UserController::addAction

