detail_element:
    path: /{_locale}/element/{slug}{anchor}
    requirements:
        _locale: "[a-z]{2}"
        slug: "^[a-z-_0-9/]+$"
        anchor: "^#[a-z-_]+$"
    defaults:
        _locale: "fr"
        anchor: ""